### ISSUE TITLE
Compatibility with Java 17 (LinkageError occurred while loading main class me.paulferlitz.Main)

### ISSUE THREAD

**Issue by edricus** [paul-eff/MinecraftOfflineOnlineConverter#4]
Hi, I have a fabric server on Debian 12
The current version of Java on my server is **openjdk 17.0.10 2024-01-16**
Is this possible to run your JAR on Java 17 ?

Error in details
```
Error: LinkageError occurred while loading main class me.paulferlitz.Main
        java.lang.UnsupportedClassVersionError: me/paulferlitz/Main has been compiled by a more recent version of the Java Runtime (class file version 64.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

**Comment by paul-eff** [comment]
I will recompile it for Java 17 and let you know when finished. Shouldn't be hard!

**Comment by paul-eff** [comment]
I added a Java 17 Jar to the [newest release](https://github.com/paul-eff/MinecraftOfflineOnlineConverter/releases).
If something doesn't work feel free to reopen the issue. Cheers.
