### ISSUE TITLE
1.20.4 Server Database mysql

### ISSUE THREAD

**Issue by Sobertimed** [paul-eff/MinecraftOfflineOnlineConverter#6]
Hey, i started my server a month ago, and i was playing in 'online-mode = true' , due a lot 'offline' player request i wanted to turn off 'online-mode', and i found your project in github, looks legit but you didn't specify what gonna happend with data where stored in Mysql database ? , like i have some plugin store data in dabase so what's gonna happen with it ? (couple plugin store the UUID inside of dabase too , like 'Lands, NexAuth, etc....')

**Comment by paul-eff** [comment]
To add to my last comment:
Don't get me wrong, this is 100% achievable! If you can interface with the database, you can look at the structure how data is stored (probably there is one location where UUIDs are matched to plugin internal IDs) and then change the UUIDs as needed.

How experienced are you with SQL or databases in general?

**Comment by Sobertimed** [comment]
thx for the reply, i was a web dev, so im pretty familiar with all databases, i see what u mean i'll backup the server file and all db data for test it out , thanks alot.

**Comment by paul-eff** [comment]
Sounds like a plan, glad to help. Have a good one!
