### ISSUE TITLE
[Bug] Using custom authservers wont work

### ISSUE THREAD

**Issue by IkyMax** [paul-eff/MinecraftOfflineOnlineConverter#7]
I recompiled the jar on java 20 with my custom API servers to fetch profiles UUID's, i'm on a Minecraft 1.20.4 Server running in pterodactyl with a Java 20 to run, it indeed can prefetch the players from the servers

`container@pterodactyl~ java -jar migrator.jar -online
Starting MinecraftOfflineOnlineConverter Version 2.3.4...
Found world name "Final" in server.properties. Trying to target this world folder.
Detected Bukkit/Spigot/Paper server.
CONVERSION: OFFLINE --> ONLINE
Was able to prefetch player Izar from usercache.json
Was able to prefetch player Greivus560 from usercache.json
Was able to prefetch player V4lcofter from usercache.json
Was able to prefetch player Min from usercache.json
Was able to prefetch player Pommiess from usercache.json
Was able to prefetch player NiKinot from usercache.json
Was able to prefetch player Lumonafu from usercache.json
Was able to prefetch player Shaki from usercache.json
Was able to prefetch player Dam_lovs_ from usercache.json
Was able to prefetch player cheeseah_ from usercache.json
Was able to prefetch player Alfie8306 from usercache.json
Was able to prefetch player Luu from usercache.json
Was able to prefetch player Spid3rDan from usercache.json
Was able to prefetch player Setco0 from usercache.json
Was able to prefetch player XxErnestopikaxX from usercache.json
Was able to prefetch player Musa from usercache.json
[...]`

but it just wont covert the uuids to online mode

`Working on playerdata...
There was a problem whilst converting the UUID from the file ./Final/playerdata/8b25c298-ded6-37cd-88ef-dcec8a90ec9a.dat. Probably offline!
There was a problem whilst converting the UUID from the file ./Final/playerdata/1f03c98a-51f9-325f-b5d6-1e257599d3de.dat. Probably offline!
There was a problem whilst converting the UUID from the file ./Final/playerdata/684ca5de-01e0-33a4-8333-ff6a1538b57c.dat. Probably offline!
There was a problem whilst converting the UUID from the file ./Final/playerdata/d6962edd-958b-359a-bfce-2d0ba72b087a.dat. Probably offline!
There was a problem whilst converting the UUID from the file ./Final/playerdata/cca400cd-fa18-314e-a94f-3df3fc762476.dat. Probably offline!
Player b0mi1 --> ab0aae9a-6538-4fb7-8ac0-7a54be308d2c to ab0aae9a-6538-4fb7-8ac0-7a54be308d2c
There was a problem whilst converting the UUID from the file ./Final/playerdata/13339273-c661-32f0-a7d6-945d5e49a4c3.dat. Probably offline!
There was a problem whilst converting the UUID from the file ./Final/playerdata/99fc0149-5200-314b-802f-68ed4737194b.dat. Probably offline!
There was a problem whilst converting the UUID from the file ./Final/playerdata/7474bfbc-4258-3f3b-8a5b-8dc718c13a69.dat. Probably offline!
There was a problem whilst converting the UUID from the file ./Final/playerdata/00000000-0000-0000-0009-000009deb3fc.dat. Probably offline!`

it just work with players who already use with online UUIDS

**Comment by paul-eff** [comment]
From my first look it seems like that basically all UUIDs that "had a problem" and "probably offline" does apply.
You can use some publicly available service to check usernames and UUIDs and they are all non existent, meaning those are all UUIDs from offline accounts. These can't be converted to online, you need a bought Minecraft account for that!

Could you please give me the whole log without leaving anything out? Either via GIT gists or Pastebin?
There is some funky stuff going on with: Player b0mi1 --> ab0aae9a-6538-4fb7-8ac0-7a54be308d2c to ab0aae9a-6538-4fb7-8ac0-7a54be308d2c 

Maybe I can find some underlying bug.
